services:
  postgres:
    container_name: postgresql
    image: postgres:latest
    environment:
      POSTGRES_DB: local_docker
      POSTGRES_USER: local_admin
      POSTGRES_PASSWORD: local_pass
    restart: on-failure
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres: